kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy-to-ec2
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd ~/pdfhero
        - bash scripts/deploy.sh

trigger:
  branch:
    - main
  event:
    - push
